Repository 21-School-Students-NN/21-school-string-plus, pull requests merged in 2025-06, with the labels that each got.

#2 Docs/workflow remove
  CHANGELOG
  RU_WORKFLOW.md
  cliff.toml
Labels: documentation

#5 Enhancement/t3 create header file
  Makefile
  hello.c
  hello.h
  s21_example_func.c
  s21_string.h
  tests.c
Labels: enhancement

#16 strerror, gcov, testing and more...
  Makefile
  README.md
  RUS_README.md
  cliff.toml
  code-samples/errlist.awk
  code-samples/errnos.awk
  code-samples/headers/errno-linux.h
  code-samples/headers/errno-xnu.h
  headers/s21_errlist.h
  headers/s21_errno.h
  headers/s21_string.h
  s21_example_func.c
  src/s21_strerror.c
  tests.c
  tests/main.c
  tests/suites.h
  tests/test_strerror.c
Labels: documentation, help wanted
